
globals_file = 'globals.p'
image_width = 1280
image_height = 720
camera_cal_folder = 'camera_cal'
camera_cal_nx6_folder = 'camera_cal_nx6'
test_images_folder = 'test_images'
test_images_nx6_folder = 'test_images_nx6'
output_folder='output_images'
camera_cal_test_folder = output_folder+'/calibration'
undistort_test_folder = output_folder+'/undistort'
persp_trans_test_folder = output_folder+'/persptrans'
thresh_test_folder = output_folder+'/thresh'
video_test_folder = output_folder+'/video'
video_project = 'project_video.mp4'
video_project_part = 'project_video_part.mp4'
video_challenge = 'challenge_video.mp4'
video_challenge_harder = 'harder_challenge_video.mp4'
video_rain = 'rain.mp4'
poly_log_name = 'poly_log.csv'
lane_width_m = 3.7
debug_log = False
